export default [
    "Threshold",
    "Imprint",
    "Gotcha",
    "Channel",
    "Sweep",
    "Radiance",
    "Hellbent",
    "Grandeur",
    "Kinship",
    "Chroma",
    "Domain",
    "Landfall",
    "Metalcraft",
    "Join forces",
    "Morbid",
    "Fateful hour",
    "Bloodrush",
    "Battalion",
    "Hero's reward",
    "Heroic",
    "Tempting offer",
    "Inspired",
    "Constellation",
    "Strive",
    "Will of the council",
    "Parley",
    "Raid",
    "Ferocious",
    "Lieutenant",
    "Formidable",
    "Spell mastery",
    "Rally",
    "Converge",
    "Delirium",
    "Council's dilemma",
    "Revolt",
    "Eminence",
    "Enrage",
    "Undergrowth",
    "Addendum",
    "Adamant",
    "Magecraft",
    "Pack tactics",
    "Coven",
    "Alliance",
    "Corrupted",
    "Celebration",
    "Paradox",
    "Descend",
    "Fathomless descent",
    "Valiant",
    "Eerie",
    "Survival"
];