// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function GetAbsolutePath(arg1:string):Promise<string>;

export function GetAppDir():Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetDataDir():Promise<string>;

export function GetStats(arg1:string):Promise<main.FileStats>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function ReadBinaryFile(arg1:string):Promise<Array<number>>;

export function ReadDirectory(arg1:string):Promise<Array<main.DirectoryEntry>>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;

export function WriteBinaryFile(arg1:string,arg2:Array<number>):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
